### ISSUE TITLE
Use ProgressLogging.jl instead of ProgressMeter?

### ISSUE THREAD

**Issue by devmotion** [PumasAI/QuartoNotebookRunner.jl#12]
I wonder if the progress bar (very nice feature BTW!) could be made backend-agnostic and better integrated in VSCode by using the ProgressLogging.jl interface (there exist eg frontends for VSCode (in the Julia extension) and the REPL (TerminalLoggers.jl)).

**Comment by MichaelHatherly** [comment]
I went with https://github.com/timholy/ProgressMeter.jl/ mostly because it appeared to be more active as a package. I'm unsure on the status of https://github.com/JuliaLogging/ProgressLogging.jl but it didn't seem as active. It's all an implementation detail so feel free to switch them out and we'll see what the different, if any there is.

**Comment by devmotion** [comment]
I guess the ProgressLogging repo is not very active because the API is quite stable. It's used a lot though since its the progress logging backend in the VSCode extension (and therefore also most of the progress logging in Pumas was switched to ProgressLogging.jl a while ago).

**Comment by andreasnoack** [comment]
I think this would be a good change since it would make the progress visualization similar to other progress meters that we use in Pumas.
