### ISSUE TITLE
Is it feasible to suppress the module name `Main.Notebook`? 

### ISSUE THREAD

**Issue by MHellmund** [PumasAI/QuartoNotebookRunner.jl#143]
test.qmd:
````
---
engine: julia
format: pdf
---

```{julia}
struct M a::Int end
x = M(22)
print(x)
```
````
output [test4.pdf](https://github.com/user-attachments/files/15513649/test4.pdf) or:

```
Main.Notebook.M(22)
```
Is it feasible to suppress the module name `Main.Notebook`?

**Comment by jkrumbiegel** [comment]
Ah that's interesting, seems that if you manually call `print`, you circumvent the mechanism we otherwise use, which prints with the `:module` context set to the current temporary module, to avoid these prefixes:

https://github.com/PumasAI/QuartoNotebookRunner.jl/blob/7fe5ace9b8522615156775e0da2d15c88d54f95b/src/QuartoNotebookWorker/src/render.jl#L228

**Comment by MHellmund** [comment]
Indeed,
````
```{julia}
import QuartoNotebookWorker
Base.stdout = QuartoNotebookWorker.with_context(stdout)

struct M a::Int end
x = M(22)
print(x)
```
````
works as desired. But I'm not such a julia guru that I could assess all side effects of using this globally.

**Comment by MHellmund** [comment]
Another remark: 
```julia
# with this line:
Base.active_module()  = Main.Notebook
# this works, too:
@show x;     
dump(x)
```
see https://github.com/JuliaLang/julia/blob/master/base/show.jl#L516-L520 and
https://github.com/JuliaLang/julia/blob/master/base/show.jl#L3073-L3077
