### ISSUE TITLE
Other output formats (Markdown, HTML)

### ISSUE THREAD

**Issue by kellertuer** [PumasAI/QuartoNotebookRunner.jl#50]
This is a great package!

I currently use Quarto Notebooks for tutorials in my documentation, where we run Quarto in the `make.jl` to render the `.qmd` files to Markdown (including the `_freeze` cache) to then include these into the docs.

Are there plans to also provide Markdown output? That would be great!

**Comment by MichaelHatherly** [comment]
Thanks @kellertuer. The current intention here is to only generate `.ipynb` output directly within this package. You should then be able to pass those generated files directly on to `quarto render file.ipynb --to <format>` where `<format>` is whatever `quarto` itself supports (via `pandoc`).

See https://github.com/PumasAI/QuartoNotebookRunner.jl/blob/8bc1e87155f0ed27b5884439a69426e8e6eaa8cd/test/utilities/prelude.jl#L61 in the tests where we do this currently.

The ultimate goal with this package is to integrate it seamlessly into `quarto` itself so that it can just be picked as an engine in your notebook's frontmatter. That's still a fair ways off, but @jkrumbiegel is currently working towards that goal.

**Comment by kellertuer** [comment]
I actually came here via Julius' PR on Quarto :)

Right, I missed that Quarto is often using Pandoc as well, so then I would probably just have to wait for the seamless integration part to use this instead of my current approach that fights quite a bit with Python dependencies before rendering ;)
