### ISSUE TITLE
Can we show a vector of plots as a tabbed panel?

### ISSUE THREAD

**Issue by pkofod** [PumasAI/QuartoNotebookRunner.jl#65]
On slack I asked if we could show a tabbed panel from a vector of plots. The idea is that pagination and separation produces a vector with elements that depend on data and models. It would be nice if this could be turned into panels that could be navigated by the viewer.

One solution that was discussed was a wrapper-type. This can have show methods defined on it. It was discussed if / when plots should be embedded or saved in separate assets.

**Comment by jkrumbiegel** [comment]
So just to recap:

Quarto uses a special markdown fencing syntax to set up panels. This has to appear in the final markdown document that quarto sends to pandoc. So in the simplest case, a panel needs at least three cells in the ipynb output, markdown fence open, asset, and markdown fence closing.

Currently, our code blocks cannot output such a sequence of blocks. The only option we have is to force all into a single block. This can be done by writing the markdown for fences and content at the same time. However, this means that there's a single `text/markdown` cell in the ipynb output, and any assets one has have to be inline-embedded into this markdown.

And this has the effect that quarto, while processing the ipynb, cannot access these `image/png` and other types of assets like it usually does, saving them into files in an asset folder structure. This means that this workaround can only be used with backend formats that support text-embedded assets, like HTML for example. Other backends like LaTeX, Word, etc. will not work.

For them, we would actually need to output the markdown, asset, markdown sequence mentioned above at the ipynb level. So this has to happen through some special cased behavior in QuartoNotebookRunner. To me it seems obvious that such a mechanism should not only exist for tabbed panels specifically, as QuartoNotebookRunner would then need to keep in sync with quarto's syntax, plus there are a lot of other possible multi-cell scenarios one can imagine, which can't all be special cased.

Therefore, we need a generic mechanism to render multiple ipynb cells using the code from a single cell. What are our options to do this?

We could add a MIME type like `MIME"QuartoNotebookRunner/multicell"` or so. Objects could then overload `show` methods for this type. However, this is kind of a hack on the display system, because we wouldn't be able to just print into some `IO` in this function. We would have to do this multiple times, for each cell, and that's not how `show` is supposed to work.

I also thought about a mechanism where one returns a vector of expressions (`quote ... end`) which are then evaluated by QuartoNotebookRunner as if they were the code of multiple cells. This does not really work though. It would only work with top-level expressions, and not expressions coming from package functions, as those expressions would always have to be treated as if they were fully escaped. So you could not reference any code not accessible in the notebook at top-level, which is quite bad.

After all, I think the simplest thing would be to add a yaml cell option which QuartoNotebookRunner can pick up on. When this flag is detected, QuartoNotebookRunner would iterate over the return type of the cell and treat each element as a separate output. This way the system is purely value based which makes composition very easy. No special types have to be defined in QuartoNotebookRunner or elsewhere, no MIME types overloaded. Maybe one could add an option to the `output` key.

Outputting three plots at once would then look something like this:

````quarto
```{julia}
#| output: multiple
[plot1, plot2, plot3]
```
````

Or for tabs something like:

````quarto
```{julia}
#| output: multiple
[markdown, plot1, markdown, plot2, markdown, plot3, markdown]
```
````

One would have to think carefully about how to integrate this with all the other cell options from quarto, though, which are all meant for single-cell output and would probably break if just used as is.

**Comment by MichaelHatherly** [comment]
Thanks for summarising. Yes using mimetypes for this isn't something we should do, and the expression escaping issue does probably make that a no go. A cell option we detect is probably the most reasonable. Let's just spend some time thinking this one over rather than rushing a solution in, there's workarounds for the time being.

**Comment by jkrumbiegel** [comment]
Here's an example of using the approach in the linked PR to create a tabset for a dynamic number of subjects. It's still pretty rough in terms of the API but the cell-expansion approach seems flexible enough.

https://github.com/PumasAI/QuartoNotebookRunner.jl/assets/22495855/89f864b5-e32f-430f-9e89-fad5e3be3906
