### ISSUE TITLE
PUMAS_VERSION UndefVarError on render

### ISSUE THREAD

**Issue by htbunn** [PumasAI/QuartoNotebookRunner.jl#82]
I've been trying out reporting in the Pumas app using quarto. There's a reproducibility section at the end of the qmd template I'm using which has the `PUMAS_VERSION` command. It works fine when I'm working interactively, but when I render to HTML I get an `UndefVarError` from the block below:

```{julia}
#| echo: false
PUMAS_VERSION
```

**Comment by vjd** [comment]
try `Main.PUMAS_VERSION`

**Comment by htbunn** [comment]
That took care of it, thank you!

**Comment by MichaelHatherly** [comment]
Code in notebooks runs in an isolated `Notebook` module such that we can re-define structs and constants that a user might have changed between notebook runs without having to pay the cost of reloading all packages in a fresh session. Since `PUMAS_VERSION` is defined in `Main` and not `Notebook` you have to, as @vjd suggested, write it with the module prefix `Main.`.

**Comment by jkrumbiegel** [comment]
Since Julia 1.9 there is the `pkgversion` function, maybe it would be clearer in the future to do `pkgversion(Pumas)`?
