### ISSUE TITLE
evaluate_raw_cells! / pwd() throws IOError: pwd(): no such file or directory

### ISSUE THREAD

**Issue by stemann** [PumasAI/QuartoNotebookRunner.jl#93]
As mentioned on https://discourse.julialang.org/t/ann-native-julia-engine-for-quarto-using-quartonotebookrunner-jl/112753/31, I ran into a strange('ish) situation where even the simplest calls to quarto/QuartoNotebookRunner failed:

```sh
~ % cat foo.qmd 
---
title: Foo
engine: julia
---

~ % quarto render foo.qmd --to md
ERROR: Julia server returned error after receiving "run" command:
Failed to run notebook: /Users/jsa/foo.qmd
ERROR: IOError: pwd(): no such file or directory (ENOENT)
Stacktrace:
  [1] uv_error
    @ ./libuv.jl:100 [inlined]
  [2] pwd()
    @ Base.Filesystem ./file.jl:63
  [3] evaluate_raw_cells!(f::QuartoNotebookRunner.File, chunks::Vector{Any}, options::Dict{String, Any}; showprogress::Bool, chunk_callback::QuartoNotebookRunner.var"#chunk_callback#61"{TCPSocket})
    @ QuartoNotebookRunner ~/.julia/packages/QuartoNotebookRunner/Mx5PG/src/server.jl:574
```

But I did move some directories around - and deleted some other ones - so I think it can be reproduced by doing:

1. Get a QuartoNotebookRunner instance running - e.g. from VS Code (using the extension) - so the instance keeps running
2. "Clean-up" - e.g. `rm -rf .quarto` etc.
3. Try to run quarto again - even from a separate terminal in another directory (that should trigger the issue)

This is further supported by the fact that killing the running julia/quarto process got quarto running again:

```sh
~ % ps -e | grep -i quarto
73190 ??         0:11.06 /Users/jsa/.julia/juliaup/julia-1.10.2+0.x64.apple.darwin14/bin/julia --startup-file=no --project=/Users/jsa/Library/Caches/quarto/julia /Applications/quarto/share/julia/quartonotebookrunner.jl /Users/jsa/Library/Caches/quarto/julia/julia_transport.txt

~ % kill -9 73190

~ % quarto render foo.qmd --to md
Starting julia control server process. This might take a while...
Precompiling project...
  1 dependency successfully precompiled in 11 seconds. 22 already precompiled.
Julia server process started.

...
```

**Comment by stemann** [comment]
Hmm... it does not reproduce right away...

It might be some strange combination of what I did:
* Running `Quarto: Preview`
* Running `Quarto: Render`
* Running `quarto render foo.md --to md` in a shell (in VS Code)
* "Clean-up"
and (perhaps) the last quarto-thing I have in my VS Code command palette history:
* Running `Quarto: Run previous cell`

But it was likely the combination with the "clean-up": It does sound like the quarto Julia process ended up running in a non-existent directory...

**Comment by stemann** [comment]
This part in the header might do it:

```md
---
project:
  execute-dir: file
---
```

And then
1. render
2. clean-up
3. render

**Comment by jkrumbiegel** [comment]
I don't quite get why I can't reproduce with your example on an M1 mac, but what fails here is a call to `pwd()` on the control server side, not the worker. 

https://github.com/PumasAI/QuartoNotebookRunner.jl/blob/f95ee95e27de27f5f33758d05cffe2ba499e015d/src/server.jl#L574

The server process is started with some working directory when you first invoke `quarto render`, and this working directory is later removed by you. Then the call to `pwd()` fails, so this server process is effectively broken as long as this directory doesn't exist (as you can't change the running process's working directory anymore).

I would think the fix is to make the server process work even if its original working directory is removed, by either removing the call to `pwd()` altogether, or by storing the original `pwd()` at startup and then reusing it for the lifetime of the server process.
